#!/usr/bin/env bash

# ArchWiki Offline Access Script
# Original Author: Nikhil Singh <nik.singh710@gmail.com>
# Package Maintainer: Semyon5700
# This script provides offline access to ArchWiki documentation

# Variables
_menu_cmd="rofi -dmenu -i -p ArchWiki "
_opener="xdg-open"
_disown=false
_lang="en"

check() {
	command -v "$1" >/dev/null 2>&1
}

notify() {
	# shellcheck disable=SC2015
	check notify-send && {
		notify-send "$@"
	} || {
		echo "$@"
	}
}

main() {
	[ -d /usr/share/doc/arch-wiki/html ] || {
		notify "arch-wiki-docs not installed"
		exit 1
	}

	wikidir="/usr/share/doc/arch-wiki/html/${_lang}"
	
	# If language directory doesn't exist, use English
	if [ ! -d "$wikidir" ]; then
		wikidir="/usr/share/doc/arch-wiki/html/en"
	fi
	
	wikidocs="$(find "${wikidir}" -iname "*.html")"

	choice=$(echo "$wikidocs" | sed -e "s|${wikidir}/||g" | sed -e "s|.html||g" | sed 's/_/ /g' | sort -n | eval "$_menu_cmd")
	[ -z "$choice" ] && exit 0
	article=$(printf "%s\n" "${wikidir}/${choice}.html" | sed 's/ /_/g')
	if $_disown; then
		$_opener "$article" &>/dev/null &
	else
		$_opener "$article"
	fi
}

help() {
	cat <<EOF
  This is a bash script for quick archwiki search using arch-wiki-docs package.

  flags:
    -h: Displays This help menu
    -d: Sets disown flag to true. e.g 'archwiki -d'
        This will disown the process after opening the entry.
        Good for using a browser like firefox and chrome. (default is false)
        *(Not recomended for terminal browsers like w3m)
    -m: Sets the menu program. e.g 'archwiki -m "rofi -dmenu -i"'
                                   'archwiki -m "bemenu"'
        This program will be used to display list of wiki entry.
        default is (${_menu_cmd[@]})
    -o: Sets the opener program. e.g 'archwiki -o firefox'
                                   'archwki -o w3m'
        This program will be used to open entry.
        default is (${_opener[@]})
    -l: Sets the language. e.g 'archwiki -l es'
                              'archwiki -l ru'
        This will set the language for wiki documentation.
        default is (${_lang})

    * Note make sure to use -h as last flag to get a preview of your choices in the help menu
EOF
}

getArgs() {
	while [ "$#" -gt 0 ]; do
		case "$1" in
		-h | --help)
			help
			exit 0
			;;
		-d)
			_disown=true
			;;
		-m)
			_menu_cmd=("$2")
			shift
			;;
		-o)
			_opener=("$2")
			shift
			;;
		-l)
			_lang=("$2")
			shift
			;;
		*)
			help
			echo ""
			echo "Wrong argument given"
			exit 1
			;;
		esac
		shift
	done
	main
}

getArgs "$@"
